#!/bin/sh

[ -f ~/.zprofile ] && source ~/.zprofile

setxkbmap -layout us,el
setxkbmap -variant ,extended
setxkbmap -option
setxkbmap -option grp:rctrl_rshift_toggle

/usr/lib/gsd-xsettings &
sleep 0.2

autorandr --change --force
hsetroot -solid "#101010"
