;; Author: Adam Lloyd <adam@alloy-d.net>
;;
;; Note: Based on the molokai theme for vim by Tomas Restrepo, which
;; is in turn based on the monokai theme for textmate by Wimer
;; Hazenberg and a darker variant by Hamish Stuart Macpherson.

(eval-when-compile
  (require 'color-theme))

(defun color-theme-molokai-ob ()
  "Color theme based on the Molokai color scheme for vim."
  (interactive)
  (color-theme-install
   '(color-theme-molokai-ob
     ((foreground-color . "#66ff66")
      (background-color . "#101010")
      (cursor-color . "#66ff66")
      (background-mode . dark))
     (default ((t (:foreground "#66ff66" :background "#101010"))))
     (bold ((t (:weight bold))))
     (bold-italic ((t (:weight bold :slant italic))))
     (custom-face-tag ((t (:foreground "#66D9EF" :weight bold))))
     (custom-state ((t (:foreground "#A6E22E"))))
     (italic ((t (:slant italic))))
     (region ((t (:background "#282828"))))
     (underline ((t (:underline t))))
     (css-selector ((t (:foreground "#F92672"))))
     (css-property ((t (:foreground "#66D9EF"))))
     (diff-added ((t (:foreground "#A6E22E" :weight bold))))
     (diff-context ((t (:foreground "#F8F8F2"))))
     (diff-file-header ((t (:foreground "#66D9EF" :background nil))))
     (diff-indicator-added ((t (:foreground "#A6E22E"))))
     (diff-indicator-removed ((t (:foreground "#F92672"))))
     (diff-header ((t (:foreground "#F8F8F2" :background "#232526"))))
     (diff-hunk-header ((t (:foreground "#AE81FF" :background "#232526"))))
     (diff-removed ((t (:foreground "#F92672"))))
     (diff-refine-change ((t (:background "#303030"))))
     (escape-glyph ((t (:foreground "#E6DB74"))))
     (minibuffer-prompt ((t (:foreground "#66D9EF"))))
     (mode-line ((t (:foreground "#654b94" :background "#1c1c1c"))))
     (mode-line-inactive ((t (:foreground "#465457" :background "#1c1c1c"))))
     (font-lock-builtin-face ((t (:foreground "#A6E22E"))))
     (font-lock-comment-face ((t (:foreground "#465457" :slant italic))))
     (font-lock-comment-delimiter-face ((t (:foreground "#465457" :slant italic))))
     (font-lock-constant-face ((t (:foreground "#AE81FF"))))
     (font-lock-doc-face ((t (:foreground "#E6DB74" :slant italic))))
     (font-lock-function-name-face ((t (:foreground "#F92672" :slant italic))))
     (font-lock-keyword-face ((t (:foreground "#66D9EF"))))
     (font-lock-negation-char-face ((t (:weight bold))))
     (font-lock-preprocessor-face ((t (:foreground "#A6E22E"))))
     (font-lock-regexp-grouping-backslash ((t (:weight bold))))
     (font-lock-regexp-grouping-construct ((t (:weight bold))))
     (font-lock-string-face ((t (:foreground "#E6DB74"))))
     (font-lock-type-face ((t (:foreground "#66D9EF"))))
     (font-lock-variable-name-face ((t (:foreground "#F92672"))))
     (font-lock-warning-face ((t (:foreground "#F8F8F2" :background "#333333"))))
     (fringe ((t (:background "#232526"))))
     (highlight ((t (:foreground "#000000" :background "#C4BE89"))))
     (hl-line ((t (:background "#293739" :foreground "#F8F8F2"))))
     (icompletep-choices ((t (:foreground "#F92672"))))
     (icompletep-determined ((t (:foreground "#A6E22E"))))
     (icompletep-keys ((t (:foreground "#F92672"))))
     (icompletep-nb-candidates ((t (:foreground "#AE81FF"))))
     (isearch ((t (:foreground "#C4BE89" :background "#303030"))))
     (isearch-fail ((t (:foreground "#F8F8F2" :background "#333333"))))
     (lazy-highlight ((t (:foreground "#AE81FF" :background "#303030"))))
     (markdown-italic-face ((t (:slant italic))))
     (markdown-bold-face ((t (:weight bold))))
     (markdown-header-face ((t (:weight normal))))
     (markdown-header-face-1 ((t (:foreground "#66D9EF"))))
     (markdown-header-face-2 ((t (:foreground "#F92672"))))
     (markdown-header-face-3 ((t (:foreground "#A6E22E"))))
     (markdown-header-face-4 ((t (:foreground "#AE81FF"))))
     (markdown-header-face-5 ((t (:foreground "#E6DB74"))))
     (markdown-header-face-6 ((t (:foreground "#66D9EF"))))
     (markdown-inline-code-face ((t (:foreground "#66D9EF"))))
     (markdown-list-face ((t (:foreground "#A6E22E"))))
     (markdown-blockquote-face ((t (:slant italic))))
     (markdown-pre-face ((t (:foreground "#AE81FF"))))
     (markdown-link-face ((t (:foreground "#66D9EF"))))
     (markdown-reference-face ((t (:foreground "#66D9EF"))))
     (markdown-url-face ((t (:foreground "#E6DB74"))))
     (markdown-link-title-face ((t (:foreground "#F92672"))))
     (markdown-comment-face ((t (:foreground "#465457"))))
     (markdown-math-face ((t (:foreground "#AE81FF" :slant italic))))
     (mumamo-background-chunk-major ((t (:background "#272822" :foreground "#F8F8F2"))))
     (mumamo-background-chunk-submode ((t (:background "#1B1D1E"))))
     (outline-1 ((t (:foreground "#66D9EF"))))
     (outline-2 ((t (:foreground "#F92672"))))
     (outline-3 ((t (:foreground "#A6E22E"))))
     (outline-4 ((t (:foreground "#AE81FF"))))
     (outline-5 ((t (:foreground "#E6DB74"))))
     (outline-6 ((t (:foreground "#66D9EF"))))
     (outline-7 ((t (:foreground "#F92672"))))
     (outline-8 ((t (:foreground "#A6E22E"))))
     (secondary-selection ((t (:background "#272822"))))
     (show-paren-match-face ((t (:foreground "#000000" :background "#FD971F"))))
     (show-paren-mismatch-face ((t (:foreground "#960050" :background "#1E0010"))))
     (widget-inactive-face ((t (:background "#D81860" :foreground "#F8F8F2"))))
     (woman-addition ((t (:foreground "#AE81FF"))))
     (woman-bold ((t (:foreground "#F92672"))))
     (woman-italic ((t (:foreground "#A6E22E"))))
     (woman-unknown ((t (:foreground "#66D9EF"))))
     (linum ((t (:background "#101010" :foreground "#517b95" :underline nil :slant normal :weight normal))))
     (linum-terminal-seperator ((t (:background "#1c1c1c" :underline nil))))
     (tabbar-default ((t (:background "#1c1c1c" :underline nil :weight normal))))
     (tabbar-unselected ((t (:background "#1c1c1c" :foreground "#465457" :underline nil :weight normal))))
     (tabbar-selected ((t (:background "#1c1c1c" :foreground "#bb1553" :underline nil :weight bold))))
     (tabbar-button ((t (:background "#1c1c1c" :foreground "#465457" :underline nil))))
     (hi-black ((t (:background "#1c1c1c" :foreground "#3c3c3c"))))
     (hi-black-b ((t (:background "#3c3c3c" :foreground "#1c1c1c" :weight bold))))
     (hi-black-hb ((t (:background "#3c3c3c" :foreground "#1c1c1c" :weight bold :height 1.50))))
     (hi-blue-b ((t (:foreground "#007388" :weight bold))))
     (hi-blue ((t (:background "#007388" :foreground "#1c1c1c"))))
     (hi-blue-b ((t (:foreground "#007388" :weight bold))))
     (hi-green ((t (:background "#30ff30" :foreground "#1c1c1c"))))
     (hi-green-b ((t (:foreground "#30ff30" :weight bold))))
     (hi-pink ((t (:background "#e53975" :foreground "#1c1c1c"))))
     (hi-red-b ((t (:foreground "#D81860" :weight bold))))
     (hi-yellow ((t (:background "#f6fd3a" :foreground "#1c1c1c"))))
     (match ((t (:background "#935bfb" :foreground "#F8F8F2"))))
     (rfc-node ((t (:bold t :foreground "#AE81FF"))))
     (rfc-xref ((t (:bold t :foreground "#AE81FF"))))
     )))

(provide 'color-theme-molokai-ob)
