monitor=eDP-1,prefered,0x0,auto
monitor=,prefered,auto-left,auto

# When lid closes then disable eDP-1
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor eDP-1,disable
# When lid opens then enable eDP-1
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor eDP-1,prefered,0x0,auto

# vim: ft=hyprlang
