exec-once = hyprctl setcursor Adwaita 24

exec-once = uwsm app -t service -s s -- waybar
exec-once = uwsm app -t service -s s -- wl-clip-persist --clipboard both
exec-once = uwsm app -t service -s s -- hypridle

exec-once = uwsm app -t service -s a -- blueman-applet
exec-once = uwsm app -t service -s a -- nm-applet --indicator
exec-once = uwsm app -t service -s a -- nextcloud
exec-once = uwsm app -t service -s a -- dropbox

# vim: ft=hyprlang
